Change filename inspect.py to model_inspect.py
* the name inspect.py causes an error (AttributeError: partially initialized module 'torch' has no attribute 'Tensor' (most likely due to a circular import))